### ISSUE TITLE
Feature request: Packet API that supports writing to a mutable Vec

### ISSUE THREAD

**Issue by whitevegagabriel** [google/pdl#74]
Currently if I want to prepend any bytes to the Vec that is generated by `to_vec`, I need to create a new Vec, write my desired bytes, then copy the Vec contents generated by `to_vec`.

However, it would be nice if a Packet had a function such as `append(&mut Vec)`.
This would eliminate the need to copy all the packet bytes, and write directly into the Vec that I have already initialized to my liking.

**Comment by hchataing** [comment]
I have planned changes for the Packet trait, let me know if that's good for your use case.
```
/// Trait implemented for all toplevel packet declarations.
pub trait Packet: Sized {
    type Parent;

    /// Try parsing an instance of Packet from the its parent representation.
    /// On success, returns the parsed object and the remaining unparsed slice.
    /// On failure, returns an error with the reason for the parsing failure.
    /// If Packet::Self is a root packet (i.e. Packet::Parent is [u8]) then the
    /// behavior of this method is the same as Packet::decode.
    fn decode_partial(buf: &Self::Parent) -> Result<Self, DecodeError>;

    /// Try parsing an instance of Packet from the input slice.
    /// On success, returns the parsed object and the remaining unparsed slice.
    /// On failure, returns an error with the reason for the parsing failure.
    fn decode_full(buf: &[u8]) -> Result<(Self, &[u8]), DecodeError>;

    /// Try parsing an instance of Packet from the input slice.
    /// Returns an error if unparsed bytes remain at the end of the input slice.
    fn decode(buf: &[u8]) -> Result<Self, DecodeError>;

    /// Return the length of the encoded packet.
    fn encoded_len(&self) -> usize;

    /// Write the packet to an output buffer.
    fn encode<T: BufMut>(&self, buf: &mut T) -> Result<(), EncodeError>;

    /// Encode the packet to a byte vector.
    fn encode_to_vec(&self) -> Result<Vec<u8>, EncodeError>;

    /// Encode the packet to a Bytes object.
    fn encode_to_bytes(&self) -> Result<Bytes, EncodeError>;
}
```

**Comment by whitevegagabriel** [comment]
Thanks!
Looks like `fn encode<T: BufMut>` fits my use case perfectly.

I personally prefer `Write` over `BufMut` to save myself an import statement, but that's just me being picky!

**Comment by marshallpierce** [comment]
BufMut is different in that it implies the write cannot fail, where as Write is for fallible I/O operations. So, I think BufMut is the right choice here since it's targeting a _buffer_ rather than a socket, etc.

**Comment by whitevegagabriel** [comment]
Ah! I have overlooked the fallibility of `Write`.

With that context, I definitely prefer the infallible `BufMut`.
